package com.demo.lab;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author muzammilmohammad
 */
public class date_and_time extends javax.swing.JPanel {

    /**
     * Creates new form date_and_time
     */
    public date_and_time() {
        initComponents();
        SimpleDateFormat timeFormat=new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        Timer timer=new Timer(1000,e->{
            Date now =new Date();
            timeclock.setText(timeFormat.format(now));
            datelabel.setText(dateFormat.format(now));
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeclock = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();

        timeclock.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        timeclock.setText("Time Loading");

        datelabel.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        datelabel.setText("               date Loading");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeclock, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeclock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("timeLabel");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel timeclock;
    // End of variables declaration//GEN-END:variables
}
